# Site
name: 'Assam AI Initiative'
description: 'Assam Artificial Intelligence Initiative (AAII – আই) is a non-profit initiative to promote various scopes of AI and build a network for students/researchers/industry persons to exchange their knowledge.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-png.png'
baseurl: ''
url : "https://aaii-axom.github.io"
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    sishir:
      name:           Sishir Kalita
      site:           https://www.wowthemes.net
      avatar:         /assets/images/sishir.jpg
      bio:            "Data Scientist at Armsoftech.air."
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    parismita:
      name:           Parismita Gogoi
      site:           https://www.wowthemes.net
      avatar:         /assets/images/parishmita.jpeg
      bio:            "Asst. Prof in the Dept. of ECE at Dibrugarh University"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet


    hridoy:
      name:           Hridoy Sankar Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/hridoy.png
      bio:            "Research Assistant at University of Cambridge, PhD in Computer Science and Engineering at IIITD, "
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    kulendu:
      name:           Kulendu Kashyap Chakraborty
      site:           https://www.wowthemes.net
      avatar:         /assets/images/kulendu.png
      bio:            "Second year student in the Dept. of Computer Science and Engineering"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      
    subhrat:
      name:           Subhrat Kishore Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/subrat.png
      bio:            "Final year student in the Dept. of Computer Science and Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    samir:
      name:           Samir Boro
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Final year student in the Dept. of Computer Science and Engineering at IIITG"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    gayatri:
      name:           Gayatri Sharma
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Second year student in the Dept. of Mechanical Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet



# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
