# Site
name: 'Assam AI Initiative'
description: 'Assam Artificial Intelligence Initiative (AAII – আই) is a non-profit initiative to promote various scopes of AI and build a network for students/researchers/industry persons to exchange their knowledge.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-png.png'
baseurl: ''
url : "https://aaii-axom.github.io"
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    sishir:
      name:           Sishir Kalita
      site:           https://www.wowthemes.net
      avatar:         /assets/images/sishir.jpg
      bio:            "Data Scientist at Armsoftech.air."
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    parismita:
      name:           Parismita Gogoi
      site:           https://www.wowthemes.net
      avatar:         /assets/images/parishmita.jpeg
      bio:            "Asst. Prof in the Dept. of ECE at Dibrugarh University"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet


    hridoy:
      name:           Hridoy Sankar Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/hridoy.png
      bio:            "Research Associate, University of Cambridge"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    kulendu:
      name:           Kulendu Kashyap Chakraborty
      site:           https://www.wowthemes.net
      avatar:         /assets/images/kulendu.png
      bio:            "Second year student in the Dept. of Computer Science and Engineering"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      
    subhrat:
      name:           Subhrat Kishore Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/subrat.png
      bio:            "Final year student in the Dept. of Computer Science and Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    samir:
      name:           Samir Boro
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Final year student in the Dept. of Computer Science and Engineering at IIITG"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    gayatri:
      name:           Gayatri Sharma
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Second year student in the Dept. of Mechanical Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

speakers:
    ankur:
      name:           Ankur Deka
      linkedin:       https://www.linkedin.com/in/ankur-deka/
      speaker-img:    /assets/images/ankur-1.jpeg
      affiliation:    Research Engineer, Intel Labs

    homanga:
      name:           Homanga Bharadwaj
      linkedin:       https://www.linkedin.com/in/homanga/
      speaker-img:    /assets/images/homanga.png
      affiliation:    PhD Scholar, CMU

    

    debanga:
      name:           Debanga Raj Neog
      linkedin:       https://www.linkedin.com/in/debanga/
      speaker-img:    /assets/images/debanga.jpg
      affiliation:    Assistant Professor, IITG

    purvi:
      name:           Purvi Agarwal
      linkedin:       https://www.linkedin.com/in/purvi-agrawal-20288725/
      speaker-img:    /assets/images/purvi.jpeg
      affiliation:    Applied Researcher-II, Microsoft 

    nagaraj:
      name:           Nagaraj Adiga
      linkedin:       https://www.linkedin.com/in/nagaraj-adiga-7a67658/
      speaker-img:    /assets/images/nagaraj.jpeg
      affiliation:    Senior Research Scientist, Zapr Media labs

    saurav:
      name:           Saurav Talukdar
      linkedin:       https://www.linkedin.com/in/stalukdar/
      speaker-img:    /assets/images/saurav.jpg
      affiliation:    Senior Control System Engineer, Google

    santonu:
      name:           Santonu Goswami
      linkedin:       https://www.linkedin.com/in/santonugoswami
      speaker-img:    /assets/images/santonu.jpeg
      affiliation:    Assoc. Professor, Azim Premji University

    biswadeep:
      name:           Biswadeep Khan
      linkedin:       https://www.linkedin.com/in/biswadeep-khan-442ba340
      speaker-img:    /assets/images/biswadeep_khan.jpg
      affiliation:    PhD Scholar, HKUST

    nabarun:
      name:           Nabarun Goswami
      linkedin:       https://www.linkedin.com/in/nabarun-goswami-28728759/
      speaker-img:    assets/images/nabarun-01.jpeg
      affiliation:    PhD Scholar, University of Tokyo

    banriskhem:
      name:           Banriskhem K. Khonglah
      linkedin:       https://www.linkedin.com/in/banriskhem-k-khonglah-60147589/
      speaker-img:    assets/images/Banriskhem.jpeg
      affiliation:    Senior Researcher, Cerence Inc.

    debmalya:
      name:           Debmalya Chakrabarty
      linkedin:       https://www.linkedin.com/in/debmalya-chakrabarty-9a650528/
      speaker-img:    assets/images/debmalya-01.jpeg
      affiliation:    Senior Applied Scientist, Amazon

    ravi:
      name:           Ravi Shankar
      linkedin:       https://www.linkedin.com/in/ravi-shankar-jhuece/
      speaker-img:    assets/images/Ravi_Shankar.png
      affiliation:    PhD Scholar, Johns Hopkins University

    # devamanyu :
    #   name:           Devamanyu Hazarika
    #   linkedin:       https://www.linkedin.com/in/devamanyu/
    #   speaker-img:    /assets/images/devamanyu.jpg
    #   affiliation:    Applied Scientist, Amazon Alexa AI

    bhaskar :
      name:           Bhaskar Deka
      linkedin:       https://www.linkedin.com/in/bhaskar-deka-62a4171/
      speaker-img:    /assets/images/bhaskardeka.jpeg
      affiliation:   Senior Vice President, EdCast

    shakuntala :
      name:           Shakuntala (Lata) Choudhury
      linkedin:       https://www.linkedin.com/in/statistician2choudhury/
      speaker-img:    /assets/images/shakuntala.jpeg
      affiliation:    Senior Director, Agadia Systems Inc.

    vikram:
      name:           CM Vikram
      linkedin:       https://www.linkedin.com/in/cm-vikram-43ba2629
      speaker-img:    /assets/images/vikram-cm.jpeg
      affiliation:    Postdoctoral Researcher at Arizona State University 

    parthana :
      name:           Parthana Majumder
      linkedin:       https://www.linkedin.com/in/prarthana-majumdar-26681613/
      speaker-img:    /assets/images/parthana.jpg
      affiliation:    Founder, Dzukou

    gaurav-baruah :
      name:           Gaurav Baruah
      linkedin:       https://www.linkedin.com/in/gaurav-baruah-87686a3b
      speaker-img:    /assets/images/gaurav.jpg
      affiliation:    Postdoctoral Scientist, Eawag Switzerland

    deep-medhi :
      name:           Deep Medhi
      linkedin:       https://www.linkedin.com/in/deep-medhi-281963
      speaker-img:    /assets/images/Deep_Medhi.jpg
      affiliation:    Program Director, National Science Foundation

    cong-zhang :
      name:           Cong Zhang
      linkedin:       https://www.linkedin.com/in/cong-zhang-oxford
      speaker-img:    /assets/images/cong-zhang.jpg
      affiliation:    Lecturer in Phonetics and Phonology, Newcastle University, UK.

    rajarshi-sarma :
      name:           Rajarshi Sarma
      linkedin:       https://in.linkedin.com/in/rajarshisarma
      speaker-img:    /assets/images/rajarshi-sarma.jpg
      affiliation:    Program Head, NEEDP, IIM Calcutta Innovation Park

    neeraj-sharma :
      name:           Neeraj Sharma
      linkedin:       https://www.linkedin.com/in/neeraj-sharma-5360ab196/
      speaker-img:    /assets/images/neeraj-sharma.jpg
      affiliation:    Neeraj Sharma, Assistant Professor, Mehta Family School of Data Science and Artificial Intelligence, IIT Guwahati

    anirudh-gupta:      
      name:           Anirudh Gupta
      linkedin:       https://www.linkedin.com/in/anirudh-gupta-a5b26622
      speaker-img:    /assets/images/anirudh-gupta.jpeg
      affiliation:    Senior Research Engineer, Gan.ai, Noida

    ranjay-krishna:      
      name:           Ranjay Krishna
      linkedin:       https://www.linkedin.com/in/ranjay-krishna-1a344444
      speaker-img:    /assets/images/ranjay_krishna.jpeg
      affiliation:    Assistant Professor, Paul G. Allen School of Computer Science & Engineering, University of Washington

    ayon-borthakur:      
      name:           Ayon Borthakur
      linkedin:       https://www.linkedin.com/in/ayonborthakur
      speaker-img:    /assets/images/ayon_borthakur.webp
      affiliation:    Assistant Professor, Department of Artificial Intelligence at IIT Hyderabad

    sanghamitra-goswami:      
      name:           Sanghamitra Goswami
      linkedin:       https://www.linkedin.com/in/sanghamitra-goswami-b8a8865
      speaker-img:    /assets/images/sanghamitragoswami.jpeg
      affiliation:    Blue Origin, California, USA

intra-aaii:
    kartik:
      name:           Kartik Agarwal
      linkedin:       https://www.linkedin.com/in/kartikaggarwal98/
      speaker-img:    /assets/images/kartik.jpeg
      affiliation:    NLP Masters student, UCSC

    sishir:
      name:           Sishir Kalita
      linkedin:       https://www.linkedin.com/in/sishirkalita
      speaker-img:    /assets/images/sishir.jpg
      affiliation:    Data Scientist at Armsoftech.air

    hridoy:
      name:           Hridoy Sankar Dutta
      linkedin:       https://www.linkedin.com/in/hridoy-sankar-dutta-18448a63/
      speaker-img:    /assets/images/hridoy.png
      affiliation:    Research Associate, University of Cambridge

    orchid:
      name:           Orchid Chetia Phukan
      linkedin:       https://www.linkedin.com/in/orchid-chetia-phukan-7ba816169
      speaker-img:    /assets/images/orchid.jpeg
      affiliation:    MTech Student, PES University, Bangalore

    ramyanee:
      name:           Ramyanee Kashyap
      linkedin:       https://www.linkedin.com/in/ramyanee-kashyap
      speaker-img:    /assets/images/ramyanee.jpeg
      affiliation:    MTech Student, IIIT Delhi, Delhi

    aniruddha:
      name:           Aniruddha Mazumdar
      linkedin:       https://www.linkedin.com/in/aniruddha-mazumdar-1aa2a5186
      speaker-img:    /assets/images/aniruddha.jpeg
      affiliation:    Data Scientist, ObaForta India

    shibani:
      name:           Shibani Das
      linkedin:       https://www.linkedin.com/in/shibani-das-083852177
      speaker-img:    /assets/images/shibani.jpeg
      affiliation:    MS Student, IIT Indore

    gayatri:
      name:           Gayatri Sharma
      linkedin:       https://www.linkedin.com/in/gayatri-sharma-1893111b2/
      speaker-img:    /assets/images/gayatri.jpeg
      affiliation:    Double majors undergraduate, IITM and AEC

    bijit:
      name:           Bijit Deka
      linkedin:       https://www.linkedin.com/in/bijit-deka
      speaker-img:    /assets/images/bijit_deka.jpeg
      affiliation:    Data Scientist, StepFunction

    ayushman:
      name:           Ayushman Buragohain
      linkedin:       https://www.linkedin.com/in/ayushman-buragohain-2145a7184/
      speaker-img:    /assets/images/ayushman_buragohain.jpeg
      affiliation:    AI Engineer, NinjaStudy

    indrajit:
      name:           Indrajit Kalita
      linkedin:       https://www.linkedin.com/in/kalita-indrajit/
      speaker-img:    /assets/images/indrajit.jpeg
      affiliation:    Research Associate, CYENS Centre of Excellence, Greece

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sishir
      avatar: /assets/images/avatar1.jpg
  # past posts
  # - scope:
  #     path: "_pastposts"
  #   values:
  #     layout: post
  #     author: hello

      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
  
# collection:
#   - past_events:
#       path: "_past_events"
#       output: true 
#   - upcoming_events:
#       output: true 

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Google Analytics
google_analytics: "" # <--- paste the TRACKING ID here.

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
