# Site
name: 'Assam AI Initiative'
description: 'Assam Artificial Intelligence Initiative (AAII – আই) is a non-profit initiative to promote various scopes of AI and build a network for students/researchers/industry persons to exchange their knowledge.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-png.png'
baseurl: ''
url : "https://aaii-axom.github.io"
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    sishir:
      name:           Sishir Kalita
      site:           https://www.wowthemes.net
      avatar:         /assets/images/sishir.jpg
      bio:            "Data Scientist at Armsoftech.air."
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    parismita:
      name:           Parismita Gogoi
      site:           https://www.wowthemes.net
      avatar:         /assets/images/parishmita.jpeg
      bio:            "Asst. Prof in the Dept. of ECE at Dibrugarh University"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet


    hridoy:
      name:           Hridoy Sankar Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/hridoy.png
      bio:            "Research Assistant at University of Cambridge, PhD in Computer Science and Engineering at IIITD, "
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    kulendu:
      name:           Kulendu Kashyap Chakraborty
      site:           https://www.wowthemes.net
      avatar:         /assets/images/kulendu.png
      bio:            "Second year student in the Dept. of Computer Science and Engineering"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
      
    subhrat:
      name:           Subhrat Kishore Dutta
      site:           https://www.wowthemes.net
      avatar:         /assets/images/subrat.png
      bio:            "Final year student in the Dept. of Computer Science and Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    samir:
      name:           Samir Boro
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Final year student in the Dept. of Computer Science and Engineering at IIITG"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    gayatri:
      name:           Gayatri Sharma
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Second year student in the Dept. of Mechanical Engineering at Assam Engineering College"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

speakers:
    ankur:
      name:           Ankur Deka
      linkedin:       https://www.linkedin.com/in/ankur-deka/
      speaker-img:    /assets/images/ankur-1.jpeg

    homanga:
      name:           Homanga Bharadwaj
      linkedin:       https://www.linkedin.com/in/homanga/
      speaker-img:    /assets/images/homanga.png

    kartik:
      name:           Kartik Agarwal
      linkedin:       https://www.linkedin.com/in/kartikaggarwal98/
      speaker-img:    /assets/images/kartik.jpeg

    debanga:
      name:           Debanga Raj Neog
      linkedin:       https://www.linkedin.com/in/debanga/
      speaker-img:    /assets/images/debanga.jpg

    purvi:
      name:           Dr. Purvi Agarwal
      linkedin:       https://www.linkedin.com/in/purvi-agrawal-20288725/
      speaker-img:    /assets/images/purvi.jpeg

    nagaraj:
      name:           Nagaraj Adiga
      linkedin:       https://www.linkedin.com/in/nagaraj-adiga-7a67658/
      speaker-img:    /assets/images/nagaraj.jpeg

    saurav:
      name:           Saurav Talukdar
      linkedin:       https://www.linkedin.com/in/stalukdar/
      speaker-img:    /assets/images/saurav.jpg

    # santonu:
    #   name:           Santonu Goswami
    #   linkedin:       https://www.linkedin.com/in/santonugoswami
    #   speaker-img:    /assets/images/santonu.jpeg

    biswadeep:
      name:           Biswadeep Khan
      linkedin:       https://www.linkedin.com/in/biswadeep-khan-442ba340
      speaker-img:    /assets/images/biswadeep_khan.jpg

    nabarun:
      name:           Nabarun Goswami
      linkedin:       https://www.linkedin.com/in/nabarun-goswami-28728759/
      speaker-img:    assets/images/nabarun-01.jpeg

    banriskhem:
      name:           Banriskhem K. Khonglah
      linkedin:       https://www.linkedin.com/in/banriskhem-k-khonglah-60147589/
      speaker-img:    assets/images/Banriskhem.jpeg

    debmalya:
      name:           Debmalya Chakrabarty
      linkedin:       https://www.linkedin.com/in/debmalya-chakrabarty-9a650528/
      speaker-img:    assets/images/debmalya-01.jpeg

    # ravi:
    #   name:           Ravi Shankar
    #   linkedin:       https://www.linkedin.com/in/ravi-shankar-jhuece/
    #   speaker-img:    assets/images/Ravi_Shankar.png

    # devamanyu :
    #   name:           Devamanyu Hazarika
    #   linkedin:       https://www.linkedin.com/in/devamanyu/
    #   speaker-img:    /assets/images/devamanyu.jpg

    # shakuntala :
    #   name:           Dr. Shakuntala (Lata) Choudhury
    #   linkedin:       https://www.linkedin.com/in/statistician2choudhury/
    #   speaker-img:    /assets/images/shakuntala.jpeg

    # ayon :
    #   name:           Dr. Ayon Borthakur
    #   linkedin:       https://www.linkedin.com/in/ayonborthakur
    #   speaker-img:    /assets/images/ayon.jpeg


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # past posts
  # - scope:
  #     path: "_pastposts"
  #   values:
  #     layout: post
  #     author: hello

      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
  
# collection:
#   - past_events:
#       path: "_past_events"
#       output: true 
#   - upcoming_events:
#       output: true 

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Google Analytics
google_analytics: "" # <--- paste the TRACKING ID here.

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
