# Site
name: 'Assam AI Initiative'
description: 'Assam Artificial Intelligence Initiative (AAII – আই) is a non-profit initiative to promote various scopes of AI and build a network for students/researchers/industry persons to exchange their knowledge.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-png.png'
baseurl: ''
url : "https://aaii-axom.github.io"
email: 'aaiiaxomi@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    sishir:
      name:           Sishir Kalita
      weblink:       https://www.linkedin.com/in/sishir-kalita-3a006120/
      avatar:         /assets/images/sishir.jpg
      bio:            "Senior Data Scientist / Speech Team Lead, Armsoftech.air"
      email:          sisiitg@gmail.com
      domain:         Speech technology, Natural Language Processing

    parismita:
      name:           Parismita Gogoi
      weblink:       https://www.linkedin.com/in/parismita-gogoi-4a264924
      avatar:         /assets/images/parishmita.jpeg
      bio:            "Asst. Prof (ECE), Dibrugarh University"
      email:          parismita@dibru.ac.in
      domain:         Speech technology

    kulendu:
      name:           Kulendu Kashyap Chakraborty
      avatar:         /assets/images/kulendu.png
      bio:            "Student, GIMT Guwahati"
      email:          imkulendu@gmail.com
      weblink:        https://kulendu.github.io
      domain:         Deep Learning, Computer Vision, Natural Language Processing

    subrat:
      name:           Subrat Kishore Dutta
      weblink:       https://www.linkedin.com/in/subrat-kishore-dutta-70a9a316b/
      avatar:         /assets/images/subrat.png
      bio:            "M.Sc. in Computer Science, Saarland University, Germany"
      email:          subratkishoredutta1234@gmail.com
      domain:         Natural Language Processing, Computer Vision, Data Visualization

    azhar:
      name:           Azharuddin Laskar
      avatar:         /assets/images/azhar.jpg
      bio:            "Senior Data Scientist, Armsoftech.air"
      email:          azharlaskar@gmail.com
      weblink:       azharlaskar.github.io
      domain:         Deep Learning Architecture, Speech Processing

    gayatri:
      name:           Gayatri Sharma
      weblink:        https://www.linkedin.com/in/gayatri-sharma-1893111b2/
      avatar:         /assets/images/gayatri.jpg
      bio:            "Double majors undergraduate, IITM and Assam Engineering College"
      email:          gayatrisharma6@yahoo.com
      domain:         Data Science, Natural Language Processing, Computer Vision 

    hridoy:
      name:           Hridoy Sankar Dutta
      weblink:       https://hridaydutta123.github.io/
      avatar:         /assets/images/hridoy.png
      bio:            "Research Associate, University of Cambridge, UK"
      email:          hridaydutta123@gmail.com
      domain:         Data-driven Cybersecurity, Social Network Analysis

    ramyanee:
      name:          Ramyanee Kashyap
      weblink:       https://www.linkedin.com/in/ramyanee-kashyap
      avatar:         /assets/images/ramyanee.jpg
      bio:            "Software Engineer, Qualcomm"
      email:          ramyanee.98@gmail.com
      domain:         Deep Learning

    abhigyan:
      name:          Abhigyan Ganguly
      weblink:       https://www.linkedin.com/in/abhigyan-ganguly-70b590160/
      avatar:         /assets/images/abhigyan.jpg
      bio:            "Software Engineer, Optum UHG"
      email:          abhigyan.nits@gmail.com
      domain:         Deep Learning, Natural Language Processing

    orchid:
      name:          Orchid Chetia Phukan
      weblink:       https://www.linkedin.com/in/orchid-chetia-phukan-7ba816169
      avatar:         /assets/images/orchid.jpg
      bio:            "PhD student, Indraprastha Institute of Information Technology Delhi (IIITD)"
      email:          orchidp@iiitd.ac.in
      domain:         Speech and Language Processing, Deep Learning

    pamir:
      name:          Pamir Gogoi
      weblink:       https://www.linkedin.com/in/pamirgogoi
      avatar:         /assets/images/pamir.jpg
      bio:            "Research Intern, Microsoft Research India"
      email:          pamir.gogoi11@gmail.com
      domain:         Speech, Natural Language Processing

    shashanka:
      name:          Shashanka Handique
      weblink:       https://www.linkedin.com/in/shashanka-handique-248055184/
      avatar:         /assets/images/shashanka.jpg
      bio:            "Software Engineer, Capgemini"
      email:          shashankahandique@gmail.com
      domain:         Graphic Designing

    shibani:
      name:          Shibani Das
      weblink:       https://www.linkedin.com/in/shibani-das-083852177
      avatar:         /assets/images/shibani.jpg
      bio:            "PhD student, Louisiana State University, USA"
      email:          shibanidas796@gmail.com
      domain:         Natural Language Processing, Knowledge Representation, Semantic Web and Reasoning

    indrajit:
      name:          Indrajit Kalita
      weblink:       https://www.linkedin.com/in/kalita-indrajit
      avatar:         /assets/images/indrajit.jpeg
      bio:            "Postdoctoral Researcher, Boston University, USA"
      email:          indrakalita09@gmail.com
      domain:         Deep Learning for Remotely Sensed Images

    ayushman:
      name:          Ayushman Buragohain
      weblink:       https://www.linkedin.com/in/ayushman-buragohain-2145a7184/
      avatar:         /assets/images/ayushman.jpg
      bio:            "Research Engineer, Dashtoon"
      email:          aburagohain160@gmail.com
      domain:         Deep Learning, Computer Vision, Natural Language Processing

    bishal:
      name:          Bishal Roy
      weblink:       https://www.linkedin.com/in/bishalr0y
      avatar:         /assets/images/bishal.jpg
      bio:            "Software Developer, Nav Prayukti Pvt Ltd."
      email:          bishalroy895@gmail.com
      domain:         DevOps

    nayan:
      name:          Nayan Moni Baishya
      weblink:       https://www.linkedin.com/in/nayan-moni-baishya-phd
      avatar:         /assets/images/nayan.jpg
      bio:            "PhD student, IIT Guwahati"
      email:          nmb94@iitg.ac.in
      domain:         Image Forensics, Computer Vision, Deep Learning Security

    mrinmoy:
      name:          Mrinmoy Bhattacharjee
      weblink:       https://mrinmoy-iitg.github.io/Webpage/index.html
      avatar:         /assets/images/mrinmoy.jpg
      bio:            "Postdoctoral Researcher, IDIAP Research Institute, Switzerland"
      email:          mrin.mb@gmail.com
      domain:         AI, Machine Learning, Speech/Audio Processing

    angana:
      name:          Angana Borah
      weblink:       https:/www.linkedin.com/in/anganaborah
      avatar:         /assets/images/angana.png
      bio:            "PhD student, University of Michigan, Ann Arbor, USA"
      email:          anganaborah10@gmail.com
      domain:         Natural Language Processing

    punyabrat:
      name:          Punyabrat Kalwar
      weblink:       https://www.linkedin.com/in/kalwar/
      avatar:         /assets/images/punyabrat.jpg
      bio:            "Masters student, IIT Kanpur"
      email:          kalwarpunya@gmail.com
      domain:         Deep Learning, Natural Language Processing

    aniruddha_bora:
      name:          Aniruddha Bora
      weblink:       https://www.linkedin.com/mwlite/in/aniruddha-bora-49b73a80
      avatar:         /assets/images/aniruddha_bora.jpg
      bio:            "Postdoctoral Research Associate, Brown University, USA"
      email:          aniruddhabora@gmail.com
      domain:         Scientific Machine Learning

    gagan:
      name:          Gagan Gayari
      weblink:       https://www.linkedin.com/in/gagangayari
      avatar:         /assets/images/gagan.jpg
      bio:            "Specialist Programmer (AI), Infosys Bangalore"
      email:          gagangayari@gmail.com
      domain:         Natural Language Processing

    bijit:
      name:           Bijit Deka
      linkedin:       https://www.linkedin.com/in/bijit-deka
      avatar:    /assets/images/bijit_deka.jpg
      affiliation:    Senior Data Scientist, StepFunction
      email:          bijitdeka23@gmail.com
      domain:         Time Series Analysis, Interpretable ML, Causal Analysis, Generative AI
    

speakers:
    ankur:
      name:           Ankur Deka
      linkedin:       https://www.linkedin.com/in/ankur-deka/
      speaker-img:    /assets/images/ankur-1.jpeg
      affiliation:    Research Engineer, Intel Labs

    homanga:
      name:           Homanga Bharadwaj
      linkedin:       https://www.linkedin.com/in/homanga/
      speaker-img:    /assets/images/homanga.png
      affiliation:    PhD Scholar, CMU

    

    debanga:
      name:           Debanga Raj Neog
      linkedin:       https://www.linkedin.com/in/debanga/
      speaker-img:    /assets/images/debanga.jpg
      affiliation:    Assistant Professor, IITG

    purvi:
      name:           Purvi Agarwal
      linkedin:       https://www.linkedin.com/in/purvi-agrawal-20288725/
      speaker-img:    /assets/images/purvi.jpeg
      affiliation:    Applied Researcher-II, Microsoft 

    nagaraj:
      name:           Nagaraj Adiga
      linkedin:       https://www.linkedin.com/in/nagaraj-adiga-7a67658/
      speaker-img:    /assets/images/nagaraj.jpeg
      affiliation:    Senior Research Scientist, Zapr Media labs

    saurav:
      name:           Saurav Talukdar
      linkedin:       https://www.linkedin.com/in/stalukdar/
      speaker-img:    /assets/images/saurav.jpg
      affiliation:    Senior Control System Engineer, Google

    santonu:
      name:           Santonu Goswami
      linkedin:       https://www.linkedin.com/in/santonugoswami
      speaker-img:    /assets/images/santonu.jpeg
      affiliation:    Assoc. Professor, Azim Premji University

    biswadeep:
      name:           Biswadeep Khan
      linkedin:       https://www.linkedin.com/in/biswadeep-khan-442ba340
      speaker-img:    /assets/images/biswadeep_khan.jpeg
      affiliation:    PhD Scholar, HKUST

    nabarun:
      name:           Nabarun Goswami
      linkedin:       https://www.linkedin.com/in/nabarun-goswami-28728759/
      speaker-img:    assets/images/nabarun-01.jpeg
      affiliation:    PhD Scholar, University of Tokyo

    banriskhem:
      name:           Banriskhem K. Khonglah
      linkedin:       https://www.linkedin.com/in/banriskhem-k-khonglah-60147589/
      speaker-img:    assets/images/Banriskhem.jpeg
      affiliation:    Senior Researcher, Cerence Inc.

    debmalya:
      name:           Debmalya Chakrabarty
      linkedin:       https://www.linkedin.com/in/debmalya-chakrabarty-9a650528/
      speaker-img:    assets/images/debmalya-01.jpeg
      affiliation:    Senior Applied Scientist, Amazon

    ravi:
      name:           Ravi Shankar
      linkedin:       https://www.linkedin.com/in/ravi-shankar-jhuece/
      speaker-img:    assets/images/Ravi_Shankar.png
      affiliation:    PhD Scholar, Johns Hopkins University

    # devamanyu :
    #   name:           Devamanyu Hazarika
    #   linkedin:       https://www.linkedin.com/in/devamanyu/
    #   speaker-img:    /assets/images/devamanyu.jpg
    #   affiliation:    Applied Scientist, Amazon Alexa AI

    bhaskar :
      name:           Bhaskar Deka
      linkedin:       https://www.linkedin.com/in/bhaskar-deka-62a4171/
      speaker-img:    /assets/images/bhaskardeka.jpeg
      affiliation:   Senior Vice President, EdCast

    shakuntala :
      name:           Shakuntala (Lata) Choudhury
      linkedin:       https://www.linkedin.com/in/statistician2choudhury/
      speaker-img:    /assets/images/shakuntala.jpeg
      affiliation:    Senior Director, Agadia Systems Inc.

    vikram:
      name:           CM Vikram
      linkedin:       https://www.linkedin.com/in/cm-vikram-43ba2629
      speaker-img:    /assets/images/vikram-cm.jpeg
      affiliation:    Postdoctoral Researcher at Arizona State University 

    parthana :
      name:           Parthana Majumder
      linkedin:       https://www.linkedin.com/in/prarthana-majumdar-26681613/
      speaker-img:    /assets/images/parthana.jpg
      affiliation:    Founder, Dzukou

    gaurav-baruah :
      name:           Gaurav Baruah
      linkedin:       https://www.linkedin.com/in/gaurav-baruah-87686a3b
      speaker-img:    /assets/images/gaurav.jpg
      affiliation:    Postdoctoral Scientist, Eawag Switzerland

    deep-medhi :
      name:           Deep Medhi
      linkedin:       https://www.linkedin.com/in/deep-medhi-281963
      speaker-img:    /assets/images/Deep_Medhi.jpg
      affiliation:    Program Director, National Science Foundation

    cong-zhang :
      name:           Cong Zhang
      linkedin:       https://www.linkedin.com/in/cong-zhang-oxford
      speaker-img:    /assets/images/cong-zhang.jpg
      affiliation:    Lecturer in Phonetics and Phonology, Newcastle University, UK.

    rajarshi-sarma :
      name:           Rajarshi Sarma
      linkedin:       https://in.linkedin.com/in/rajarshisarma
      speaker-img:    /assets/images/rajarshi-sarma.jpg
      affiliation:    Program Head, NEEDP, IIM Calcutta Innovation Park

    neeraj-sharma :
      name:           Neeraj Sharma
      linkedin:       https://www.linkedin.com/in/neeraj-sharma-5360ab196/
      speaker-img:    /assets/images/neeraj-sharma.jpg
      affiliation:    Neeraj Sharma, Assistant Professor, Mehta Family School of Data Science and Artificial Intelligence, IIT Guwahati

    anirudh-gupta:      
      name:           Anirudh Gupta
      linkedin:       https://www.linkedin.com/in/anirudh-gupta-a5b26622
      speaker-img:    /assets/images/anirudh-gupta.jpeg
      affiliation:    Senior Research Engineer, Gan.ai, Noida

    ranjay-krishna:      
      name:           Ranjay Krishna
      linkedin:       https://www.linkedin.com/in/ranjay-krishna-1a344444
      speaker-img:    /assets/images/ranjay_krishna.jpeg
      affiliation:    Assistant Professor, Paul G. Allen School of Computer Science & Engineering, University of Washington

    ayon-borthakur:      
      name:           Ayon Borthakur
      linkedin:       https://www.linkedin.com/in/ayonborthakur
      speaker-img:    /assets/images/ayon_borthakur.webp
      affiliation:    Assistant Professor, Department of Artificial Intelligence at IIT Hyderabad

    sanghamitra-goswami:      
      name:           Sanghamitra Goswami
      linkedin:       https://www.linkedin.com/in/sanghamitra-goswami-b8a8865
      speaker-img:    /assets/images/sanghamitragoswami.jpeg
      affiliation:    Blue Origin, California, USA

intra-aaii:
    kartik:
      name:           Kartik Agarwal
      linkedin:       https://www.linkedin.com/in/kartikaggarwal98/
      speaker-img:    /assets/images/kartik.jpeg
      affiliation:    NLP Masters student, UCSC

    sishir:
      name:           Sishir Kalita
      linkedin:       https://www.linkedin.com/in/sishirkalita
      speaker-img:    /assets/images/sishir.jpg
      affiliation:    Senior Data Scientist / Speech Team Lead, Armsoftech.air

    hridoy:
      name:           Hridoy Sankar Dutta
      linkedin:       https://www.linkedin.com/in/hridoy-sankar-dutta-18448a63/
      speaker-img:    /assets/images/hridoy.png
      affiliation:    Research Associate, University of Cambridge

    orchid:
      name:           Orchid Chetia Phukan
      linkedin:       https://www.linkedin.com/in/orchid-chetia-phukan-7ba816169
      speaker-img:    /assets/images/orchid.jpeg
      affiliation:    PhD student, Indraprastha Institute of Information Technology Delhi

    ramyanee:
      name:           Ramyanee Kashyap
      linkedin:       https://www.linkedin.com/in/ramyanee-kashyap
      speaker-img:    /assets/images/ramyanee.jpg
      affiliation:    Software Engineer, Qualcomm

    aniruddha:
      name:           Aniruddha Mazumdar
      linkedin:       https://www.linkedin.com/in/aniruddha-mazumdar-1aa2a5186
      speaker-img:    /assets/images/aniruddha.jpeg
      affiliation:    Data Scientist, ObaForta India

    shibani:
      name:           Shibani Das
      linkedin:       https://www.linkedin.com/in/shibani-das-083852177
      speaker-img:    /assets/images/shibani.jpeg
      affiliation:    PhD student, Louisiana State University, USA

    gayatri:
      name:           Gayatri Sharma
      linkedin:       https://www.linkedin.com/in/gayatri-sharma-1893111b2/
      speaker-img:    /assets/images/gayatri.jpg
      affiliation:    Double majors undergraduate, IITM and AEC

    bijit:
      name:           Bijit Deka
      linkedin:       https://www.linkedin.com/in/bijit-deka
      speaker-img:    /assets/images/bijit_deka.jpg
      affiliation:    Senior Data Scientist, StepFunction

    ayushman:
      name:           Ayushman Buragohain
      linkedin:       https://www.linkedin.com/in/ayushman-buragohain-2145a7184/
      speaker-img:    /assets/images/ayushman.jpg
      affiliation:    Research Engineer, Dashtoon

    indrajit:
      name:           Indrajit Kalita
      linkedin:       https://www.linkedin.com/in/kalita-indrajit/
      speaker-img:    /assets/images/indrajit.jpeg
      affiliation:    Postdoctoral Researcher, Boston University, USA

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sishir
      avatar: /assets/images/avatar1.jpg
  # past posts
  # - scope:
  #     path: "_pastposts"
  #   values:
  #     layout: post
  #     author: hello

      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
  
# collection:
#   - past_events:
#       path: "_past_events"
#       output: true 
#   - upcoming_events:
#       output: true 

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Google Analytics
google_analytics: "" # <--- paste the TRACKING ID here.

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
